services:
  - type: web
    name: care-compass-capstone-api
    env: node
    plan: free
    autoDeploy: true
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: care-compass-capstone
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: care-compass-capstone
    env: static
    autoDeploy: true
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: care-compass-capstone-api
          envVarKey: RENDER_EXTERNAL_URL
